### ISSUE TITLE
Agent Metrics not working 

### ISSUE THREAD

**Issue by jansouza** [GoogleCloudPlatform/sapagent#10]
Agent Metrics not working and I don't see any error on logs.

sap/agent/cpu/utilization
sap/agent/health
sap/agent/memory/utilization

Agent version: 2.8

**Comment by megelatim** [comment]
Thanks for reaching out.  Can I get some more information from you?

1. What OS are you using (distribution + version)?
2. How did you install the agent (via package manager)?
3. What is in your configuration (content of /etc/google-cloud-sap-agent/configuration.json)?

**Comment by megelatim** [comment]
One more thing, the agents metrics are not collected unless you enable it in your configuration, so add the following to your /etc/google-cloud-sap-agent/configuration.json:

`"collect_agent_metrics": true`

**Comment by jansouza** [comment]
Hi, @megelatim, thanks for you response ...

1. SUSE Linux Enterprise Server 15 SP5
2. Yes, use this doc https://cloud.google.com/solutions/sap/docs/agent-for-sap/latest/install-config-on-vm#sles-15
3. {
  "provide_sap_host_agent_metrics": true,
  "log_level": "INFO",
  "log_to_cloud": true,
  "collection_configuration": {
    "collect_workload_validation_metrics": true,
    "workload_validation_db_metrics_frequency": 3600,
    "collect_process_metrics": true,
    "process_metrics_frequency": 5,
    "slow_process_metrics_frequency": 30,
    "sap_system_discovery": true
  },
  "hana_monitoring_configuration": {
    "enabled": false
  }
}

I didn't see this configuration (collect_agent_metrics) at documentation, i'll try.

Thanks

**Comment by megelatim** [comment]
We will update the public google cloud documentation to include this configuration option, apologies that it was not included to begin with

**Comment by jansouza** [comment]
Now worked.
Thank you
