### ISSUE TITLE
Log files are world-writable.

### ISSUE THREAD

**Issue by natedogith1** [GoogleCloudPlatform/sapagent#16]
The log files are set to world-writable.  It looks like this is done here: https://github.com/GoogleCloudPlatform/sapagent/blob/1e926c36b8448b1c72edbf2b11d4abf76672aad2/internal/onetime/onetime.go#L158

These log files are triggering security findings.

**Comment by karkunpavan** [comment]
Hi @natedogith1 , thanks for raising the issue.

I can explain the rationale for having the logs writable by other users in the Agent for SAP. 

The onetime executions(such as backint, hanadiskbackup etc) can be run by multiple users on the machine. Let us take a scenario where 
- user-1 ran the one time execution and this created a /var/log/google-cloud-sap-agent/backint.log file.
- Another user say sidadm-1 runs the backint command - they should still be able to write to the same log file.
 
If the log file did not have a world write the log to write would fail for any user other than the one who created it.

Let me know if this addresses your concerns.

**Comment by natedogith1** [comment]
Our security requirements (based off of CIS Benchmarks) requires that all world-writable directories have their sticky bit set and that there are no world writable files.  I haven't seen this issue before with other software, but if this is a requirement we can probably document an exception.

**Comment by karkunpavan** [comment]
Thanks - We will add comments in code and update public docs indicating why we do this.

**Comment by karkunpavan** [comment]
Commit [6994cc9](https://github.com/GoogleCloudPlatform/sapagent/commit/6994cc9ab2a995f101d5798b183f4cb19bb1c378) fixes this issue. the fix will be part of the upcoming release of the agent.
