### ISSUE TITLE
Vendoring dependencies not possible for distro packaging

### ISSUE THREAD

**Issue by glaubitz** [GoogleCloudPlatform/sapagent#2]
I'm trying to update `sapagent` for SLE using SUSE's `obs-service-go_modules` OBS module which automatically creates a `vendor.tar.gz` tarball.

However, that fails due `go-yaml` missing in the `go.mod` file:

```
glaubitz@suse-laptop:~/suse/ibs/home:glaubitz:branches:SUSE:SLE-15-SP1:Update/google-cloud-sap-agent.SUSE_SLE-15-SP1_Update/sapagent> go mod vendor
github.com/GoogleCloudPlatform/sapagent/internal/utils/yamlpb imports
        github.com/go-yaml/yaml: no required module provides package github.com/go-yaml/yaml; to add it:
        go get github.com/go-yaml/yaml
glaubitz@suse-laptop:~/suse/ibs/home:glaubitz:branches:SUSE:SLE-15-SP1:Update/google-cloud-sap-agent.SUSE_SLE-15-SP1_Update/sapagent>
```

Could `go-yaml` be added to `go.mod`?

FWIW, the following change does not work:

```go
diff --git a/go.mod b/go.mod
index 0420e45..4cbd275 100644
--- a/go.mod
+++ b/go.mod
@@ -27,6 +27,7 @@ require (
   google.golang.org/api v0.110.0
   google.golang.org/genproto v0.0.0-20230222225845-10f96fb3dbec
   google.golang.org/protobuf v1.30.0
+  github.com/go-yaml/yaml v3.0.1
 )
 
 require (
```

```
glaubitz@suse-laptop:~/suse/ibs/home:glaubitz:branches:SUSE:SLE-15-SP1:Update/google-cloud-sap-agent.SUSE_SLE-15-SP1_Update/sapagent> go mod vendor
go: errors parsing go.mod:
/home/glaubitz/suse/ibs/home:glaubitz:branches:SUSE:SLE-15-SP1:Update/google-cloud-sap-agent.SUSE_SLE-15-SP1_Update/sapagent/go.mod:30:3: require github.com/go-yaml/yaml: version "v3.0.1" invalid: should be v0 or v1, not v3
glaubitz@suse-laptop:~/suse/ibs/home:glaubitz:branches:SUSE:SLE-15-SP1:Update/google-cloud-sap-agent.SUSE_SLE-15-SP1_Update/sapagent>
```

**Comment by karkunpavan** [comment]
Hi @glaubitz, thanks for reporting this. I have fixed this in [7bb3b1a](https://github.com/GoogleCloudPlatform/sapagent/commit/7bb3b1aade0f04294819c894dc4f9cacdd94d952) let me know if it works now.

**Comment by glaubitz** [comment]
Thanks. Could you tag v1.6 so I can just use that for packaging? This makes the workflow easier for me.

**Comment by karkunpavan** [comment]
I am going to tag this as 1.5.1 - hope that works for you.

We are maintaining a 1:1 mapping between tags and the agent versions that are released thru package managers.

**Comment by glaubitz** [comment]
Of course, that's fine. Thanks a lot for the quick fix!

**Comment by glaubitz** [comment]
Let me know once the tag is there.

**Comment by karkunpavan** [comment]
Sounds good, tag v1.5.1 is created at commit [7bb3b1a](https://github.com/GoogleCloudPlatform/sapagent/commit/7bb3b1aade0f04294819c894dc4f9cacdd94d952)

Thanks!
